# [A6] Data Management Project – report and database realisation

Realisation of the spatial database previously designed in the project design proposal. 

The report should recapitulate the main aims of the project, the approach taken by the team, link main requirements to the capabilities of the implemented database system and its interaction with a GIS client, if appropriate. If an interaction with the GIS client is considered, the visualisations used should be of cartographically sound quality, with consistent use of cartographic symbology appropriate to the use case (see project [resources](./project_resources.qmd)). 

The report should provide a documentation of the final logical design used, discuss technical choices of note in the final realisation, outline how the database was populated with appropriate (possibly made up) data, and demonstrate that the database system is able to adequately support the analytical requirements noted in the design brief [project_specification](project_specification.qmd).

Do not forget to explicitly address ethical considerations, including data access and use, and data sovereignty. 

This is a group assessment. The deliverables are: a report of a maximum of 15 pages (per group) (35 points), the realised implementation passing acceptance criteria, and a 1-page reflection per individual student (10 points). Check submission instructions at the end of this page.

This assessment should require about 50 hours to complete.


## Assignment report components

- **Documentation: from requirements to implementation [7 pts]:**  The documentation of the mapping from requirements to implementation, with supporting arguments for technical choices. Documentation of what requirements have been met, which have been supplemented by designer's choices (and why), or not satisfied by the implementation (possibly because it is not possible to satisfy them for computational or technical reasons). 
- **Documentation: technical aspects [7 pts]:** Documentation of the final implemented logical model, and discussion of the choices made to deal with database performance, integrity management during updates of the data;
- **Documentation: functionality/analytical capabilities [7 pts]:** Documentation of the implemented analytical and data management capabilities based on the identified requirements, with demonstration queries and query results, where applicable. The implementation is based on sound technically and conceptual use of the DBMS, incl custom functionality where suitable;
- **Demonstration SQL code [5 pts]:** professionally formatted, seamlessly executable code with inline documentation to demonstrate the analytical capabilities of the realised database, including, where applicable, sample insert or update queries demonstrating the data management capabilities based on simple sample inputs.
- **Data sources and data ingestion and processing [5 pts]:** Annotated and referenced sources of data used, incl. the rational for why they were chosen. Documentation of the data processing and ingestion pipeline with characterisation of the final storage structures for all data used.
- **Report presentation [4 pts]:** professional-level formatting, structure, grammar and writing style, illustration with diligently cross-referenced figures with meaningful captions, and proper citations/referencing. 

## Individual reflection components

+ **Individual reflection [10 pts]:** a professional-level, brief and to the point reflection structured along the aspects of (a) Situation, (b) Approach taken to address the situation, and (c) Outcome, for :
 - A **Technical challenge** you encountered, across the entire project;
 - A **Spatial challenge** you encountered, specifically relating to a problem with thinking about the spatial requirements, conceptual modeling of spatial aspects of the project, or relating to the data envisaged;
 - An **Interpersonal/teamwork challenge** reflecting on your role in the team and contribution, team dynamics and collaboration management, possibly including your own or the team's individual strengths and weaknesses. 

Note: A reflection should be honest, deep, personal, and beyond a single, technical issue. A reflection on your personal working style, abilities, and qualities is key to grow as a scientist and engineer. Also check the module on Canvas with links to University resources about reflections.

Detailed rubric for the group report is presented below (**35 pts total**):

|     Criteria    	|     Exceeds expectations (6 to 7 pts)    	|     Meets expectations (4 to 6   pts)    	|     Approaches expectations (2 to 4   pts)    	|     Below expectations (1 to 2 pts)    	|     Insufficient (<=1 pt)    	|
|---	|---	|---	|---	|---	|---	|
|     **Documentation: from requirements to implementation**    	|     The   requirements are thoroughly documented and mapped to the approach taken from design to implementation. The report makes if clear where requirements have been met, supplemented by designer's choices ( clearly argued), or not satisfied by the implementation (possibly because it is not possible to satisfy them for computational or technical reasons). |      The   requirements are well documented and mapped to the approach taken from design to implementation. The report is mostly clear where requirements have been met, supplemented by designer's choices, or not satisfied by the implementation for computational or technical reasons, although this reasoning is lacking in minor points. |     The   requirements are mostly well documented and mapped to the approach taken from design to implementation, although there are decisions made without sufficient support/documentation. The report is in places unclear about what requirements have been met, or why and how they have been supplemented by designer's choices. Reasoning about requirements not implemented is lacking in thoroughness.	|      The   requirements are weakly  mapped to the approach taken from design to implementation, with frequent decisions made without sufficient support/documentation. The report is unclear about what requirements have been met, or why and how they have been supplemented by designer's choices. Reasoning about requirements not implemented is insufficiently thorough.	|     The   requirements are not  mapped to the approach taken, or do not cover the entire progress from design to implementation. Decisions may be noted without support and documentation. The report is unclear about what requirements have been met.	   	|
|     **Documentation: technical aspects**    	|     Professionally documented implementation of the logical model proposed, with deeply argued discussion of grounded technical choices made. Well demonstrated ability to assure database integrity through during updates, and considerations for the performance of the intended queries.	|    Clearly and comprehensively documented implementation of the logical model proposed, with well argued discussion of technical choices made. Demonstrated ability to assure database integrity through during updates, with some considerations for the performance of the intended queries.	 	|      Clearly and sufficiently documented implementation of the logical model proposed with only minor uncertainty about the choices made, possibly with only descriptive rather than analytical discussion. Demonstrated ability to assure database integrity through most updates types, with patchy considerations for the performance of the intended queries.|    Patchy documentation of the implementation of the logical model proposed with common uncertainty about the choices made. Discussion of the choices is descriptive, and possibly incomplete, rather than analytical. Demonstrated ability to assure database integrity through most updates types, with patchy considerations for the performance of the intended queries.|   Inadequate documentation of the implementation of the logical model with major uncertainty about the choices made. No discussion of the technical choices. Low ability to maintain database integrity through updates of data, and low considerations for the performance of the intended queries.  	|
|     **Documentation: analytical capabilities**    	|    Demonstrates that the implementation is able to elegantly perform the analytical and data management needs identified in the requirements analysis, and possibly beyond based on the additionally identified needs. Makes technically or conceptually elegant analytical choices, and proposes innovative solutions to some of the vague requirements, or elegantly navigates around the analytical limitations  of the target DBMS, incl by implementing custom functionality. 	|     Demonstrates that the implementation is able to perform analytical and data management needs identified in the requirements analysis, with attempts to support additional functionality based on the requirements analysis. Makes sound technical or conceptual analytical choices, and proposes feasible solutions to some of the vague requirements, or clearly demonstrates why some functionalities can not be satisfied because of the  analytical limitations  of the target DBMS, incl if considering implementing custom functionality of moderate complexity.    	|     Demonstrates that the implementation is able to perform most analytical and data management needs identified in the requirements analysis, with little to no attempt to support additional functionality based on the requirements analysis. Makes at times unsound technical or conceptual analytical choices, and proposes at times inelegant solutions to some of the requirements. Little or unsuccessful attempts to convincingly demonstrate why some functionalities can not be satisfied by the target DBMS. No attempt to extend the approach by implementing custom functionality of moderate complexity.      	|     Weak demonstration that the implementation is able to perform some of the analytical and data management needs identified in the requirements analysis, with no attempt to support additional functionality based on the requirements analysis. Makes at times poor technical or conceptual analytical choices, and frequently proposes inelegant solutions to the requirements. No attempts to convincingly demonstrate why some functionalities can not be satisfied by the target DBMS. No attempt to extend the approach by implementing custom functionality of any complexity.    	|     Flawed demonstration of the analytical capabilities of the implementation, on many needs identified in the requirements analysis, without additional functionality. Frequent poor technical or conceptual analytical choices, missing solutions to some of the requirements. Attempts to convince that capabilities present in the DBMS are insufficient for common analyses.  	|

|     Criteria    	|     Exceeds expectations (4 to   5 pts)    	|     Meets expectations (3 to 4   pts)    	|     Approaches expectations (2 to 3   pts)    	|     Below expectations (1   to 2 pts)    	|     Insufficient (<=1 pt)    	|
|---	|---	|---	|---	|---	|---	|
|     **Demonstration SQL code**    	|   Professionally formatted, seamlessly executable code with thorough inline documentation to demonstrate the analytical capabilities of the realised database, including, where applicable, sample insert or update queries demonstrating the data management capabilities based on simple sample inputs. Relates directly and clearly to the above documentation without ambiguity. |     Well formatted, mostly seamlessly executable code with robust inline documentation to demonstrate the analytical capabilities of the realised database, including sample insert or update queries demonstrating most aspects of the data management capabilities of the database based on simple sample inputs. Relates directly to the above documentation without significant ambiguity.    	|     Well formatted, mostly seamlessly executable code with somewhat ambiguous inline documentation to demonstrate the majority of the analytical capabilities of the realised database, including sample insert or update queries demonstrating the main aspects of the data management capabilities of the database based on simple sample inputs. Relates directly to the above documentation with some ambiguity.       	|     Valid SQL code formatted with lack of consistency but executable without editing, possibly requiring first understanding of the documentation to interpret its purpose or actions. Inconsistent demonstration of some of the analytical capabilities of the realised database, possibly missing some sample insert or update queries needed for the demonstration of aspects of the data management capabilities of the database. Alternatively, sample inputs too complex, beyond the requirements of basic demonstration of the capabilities. Does not relate well to the overall documentation.       	|     Flawed or invalid SQL code formatted with no consistency, possibly requiring some editing to execute and difficult to understand. Inconsistent demonstration of many of the analytical capabilities of the realised database, possibly missing numerous sample insert or update statements needed for the demonstration of the data management capabilities of the database. Sample inputs are either missing or too complex, beyond the requirements of basic demonstration of the capabilities. Does not relate well to the overall documentation. |
|     **Data sources and data ingestion and processing**    	|     Identifies   and uses only appropriate data sources for the implemented spatial database. The data sources used are always relevant to the problem domain and are integrated effectively into the spatial database. The processing pipeline, the input data requirements, and the output dataset metadata are documented to a professional standard. Demonstrates an outstanding understanding of data quality management techniques and data processing/loading requirements. Demonstrates a professional understanding of data quality management techniques and data processing/loading requirements. 	|     Identifies and uses appropriate data sources for the implemented spatial database. The data sources used are relevant to the problem domain and are integrated effectively into the spatial database with only minor departures from best practice. The processing pipeline, the input data requirements, and the output dataset metadata are documented to a high standard with only minor uncertainties. Demonstrates a strong understanding of data quality management techniques and data processing/loading requirements.    	|     Identifies and uses mostly appropriate data sources for the implemented spatial database. The data sources used are mostly relevant to the problem domain and are integrated with minor inefficiencies  into the spatial database with occasional departures from best practice. The processing pipeline, the input data requirements, and the output dataset metadata are documented to with some uncertainties, but would enable to understand the core functionality of the data pipeline. Demonstrates a passable understanding of data quality management techniques and data processing/loading requirements.     	|     Identifies and occasionally uses inappropriate data sources, or misses important data for the implementation of the required spatial database. The data sources used are at times irrelevant to the problem domain or are integrated ineffectively into the spatial database with frequent departures from best practice. The processing pipeline, the input data requirements, and the output dataset metadata are documented to at times unclear, possibly impacting on the understanding of aspects of the data pipeline. Demonstrates a weak understanding of data quality management techniques and data processing/loading requirements.     	|     Frequently misses important, or uses irrelevant, or low quality data sources for the implementation. The data sources used are inadequate to the problem domain or are integrated ineffectively into the spatial database with frequent departures from best practice. The processing pipeline, the input data requirements, and the output dataset metadata are poorly documented, making it difficult/impossible to understand aspects of the approach. Demonstrates an insufficient  understanding of data quality management techniques and data processing/loading requirements.    	|


|     Criteria    	|      Meets expectations (3 to 4   pts)    	|     Approaches expectations (2 to 3   pts)    	|     Below expectations (1   to 2 pts)    	|     Insufficient (<=1 pt)    	|
|---	|---	|---	|---	|---	|---	|
|     **Report   Presentation**    	|   Professional and effective presentation of the project. The report follows a standard technical report structure and clearly describes the link between project requirements, design decisions, the implemented functionality, and the demonstration of the functionality (as SQL queries and their outputs). Report uses and appropriate writing style. Report includes visual aids such as diagrams, tables, and maps of professional quality (publication ready) to support the text. Uses attributions and references to all sources. The report is accompanied by a well formatted SQL file, clearly identifying queries that realise the requirements of the project and a number of additional exciting capabilities. 	|     Presents the project in a report that follows a standard technical report structure and describes the link between project requirements and design decisions, with only minor inconsistencies with the implemented solution, possibly manifest in the demonstration of the functionality. Report uses and appropriate writing style. Includes adequate visual aids such as diagrams, tables and maps to support the text, with a good level of graphical presentation (publishable after minor tweaks). Attributes external sources and references without flaws. The report is accompanied wby a well formatted SQL file, clearly identifying queries that realise all the requirements of the project. |    Presents the project in a report that mostly follows a standard technical report structure. The description of the link between project requirements, design decisions and implementation is in places not well specified, or is in minor aspects inconsistent with the implemented solution, or inconsistent with the functionality demonstrated by the demonstration queries. Report uses a mostly appropriate writing style, departing from clear and succinct technical writing ( e.g., terminology) only in a few places. The visual aids such as diagrams, tables and maps that support the text have a good level of graphical presentation but not sufficient for publication. Attribution of external sources and references has only minor flaws (typos, missing elements of the attribution such as page numbers). The report is accompanied wby a well formatted SQL file, clearly identifying queries that realise most of the requirements of the project. |     Presents the project in a report that departs from the qualities expected from a technical report structure. The description of the link between project requirements, design decisions and implementation is frequently flawed, or is in major aspects inconsistent with the implemented solution. Report uses a non-technical writing style, is in places unclear and overly verbose, and does not consistently use correct terminology. The visual aids such as diagrams, tables and maps to support the text are lacking in a number of places where their use would be appropriate.  The level of graphical presentation is insufficient, and not undertaken with care. The attribution of external sources and references has more significant flaws, *even if* it is still possible to (after effort) identify the referenced document. The report is accompanied by an SQL file only somewhat identifying queries that realise some of the requirements of the project, but not all.	|     

<!--Presents the project in a report that significantly departs from the qualities expected from a technical report structure. The description of the link between project requirements, design decisions and implementation is frequently flawed and in major aspects inconsistent with the implemented solution, including the demonstrated capabilities. Report frequently uses a non-technical writing style, is unclear and overly verbose or insufficiently detailed, and consistently uses incorrect terminology. The visual aids such as diagrams, tables and maps to support the text are either missing or the level of graphical presentation is insufficient. The attribution of external sources and references has significant flaws, and it may be impossible to identify the referenced document, or  references are missing altogether. The report is accompanied either by a incorrectly formatted SQL file, or this file does not clearly identifying queries that realise identifiable requirements of the project.  	|
-->

The assessment of the individual reflection will be assessed based on the following rubric (**10 pts total**):

|     Criteria    	|     Outstanding (8 to   10 pts)    	|     Deep, broad and critical reflection (6 to 8 pts)    	|     Balanced reflection (4 to 6   pts)    	|     Descriptive but shallow (2 to 4 pts)    	|     Weak (<=2 pts)    	|
|---	|---	|---	|---	|---	|---	|
|     **Individual   Reflection**    	|     Highly reflective   response. Demonstrates the ability to critically consider and assess own contributions to the project by reflecting on challenges, reflecting on strategies that enabled to resolve them, and the outcomes achieved, including learning for the future incl. self-development.    	|     Reflective   response. Considers and attempts to assess challenges, approaches taken and results achieved.   	|     Somewhat reflective response. Tends to describe rather than reflect on challenge, the reflection on the appraoch taken is somewhat shallow and it is not clear how the outcomes inform change in future behaviour.   	|     A reflection on individual challenge during the undertaking of the task is not evident, and the outcomes and not supported by sufficient ellaboration on the approach taken. Little to not reflection on learnings for the future. 	|     A reflection on  the challenges, approaches and outcomes along the three kinds of challenges is missing or incomplete. The description of individual learning/growth is either unconvincing or lacking.    	|

## Submission guidelines

1. Submit into Assignment 6.1 on Canvas:
    - A **report** of a maximum of 15 pages per group (exclusive of appendices for the final Logical ER diagram and data dictionary/specification of the implemented system) (35 pts total)
    - A first **SQL file** documenting your **database setup (data creation and insertion)** processes in the form of SQL commands. For data import processes that were done using non-SQL functionalities (e.g. QGIS or command line tools, Python scripts), describe these processes in SQL comments (lines beginning with `--`). The markers will not execute this SQL file but will look over it as part of the assessment process;
    - A second **SQL file** with the SQL `INSERT` or `SELECT` statements that **demonstrate the requested functionality**, both ones that run, as well as those that need to fail by design. These queries should be able to be executed on Wammawatcha by the markers. Clear and extensive commenting is expected.
2. A separate submission (Assignment 6.2 in Canvas) of **a 1-page self-reflection** *per individual student* (10 pts). 

